_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 8dfc7768-4ee6-4a96-837e-a5b785fa4d68
name: 'Innoraft Employee Management Portal'
mail: admin@example.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
